const GADGET_DATABASE = {
    'ARMOR10000': {'id': 'ARMOR10000', 'name': 'Armor10000', 'type': 'DEFENSE'},
    'ARMOR5000': {'id': 'ARMOR5000', 'name': 'Armor5000', 'type': 'DEFENSE'},
    'ARMORABLATIVE': {'id': 'ARMORABLATIVE', 'name': 'Armorablative', 'type': 'DEFENSE'},
    'ARMORCHITIN': {'id': 'ARMORCHITIN', 'name': 'Armorchitin', 'type': 'DEFENSE'},
    'ARMORCOMPOSITE': {'id': 'ARMORCOMPOSITE', 'name': 'Armorcomposite', 'type': 'DEFENSE'},
    'ARMORDUSK': {'id': 'ARMORDUSK', 'name': 'Armordusk', 'type': 'DEFENSE'},
    'ARMORFIGHTER': {'id': 'ARMORFIGHTER', 'name': 'Armorfighter', 'type': 'DEFENSE'},
    'ARMORMOLECULAR': {'id': 'ARMORMOLECULAR', 'name': 'Armormolecular', 'type': 'DEFENSE'},
    'ARMORORGANIC': {'id': 'ARMORORGANIC', 'name': 'Armororganic', 'type': 'DEFENSE'},
    'ARMORREFLECTIVE': {'id': 'ARMORREFLECTIVE', 'name': 'Armorreflective', 'type': 'DEFENSE'},
    'ARMORSTANDARD': {'id': 'ARMORSTANDARD', 'name': 'Armorstandard', 'type': 'DEFENSE'},
    'ARMORSTEALTH': {'id': 'ARMORSTEALTH', 'name': 'Armorstealth', 'type': 'DEFENSE'},
    'AUTOREPAIR': {'id': 'AUTOREPAIR', 'name': 'Autorepair', 'type': 'UTILITY', 'energyCost': 0},
    'BEACON100': {'id': 'BEACON100', 'name': 'Beacon100', 'type': 'WEAPON', 'energyCost': 80, 'cooldown': 5000, 'damage': 0, 'range': 30, 'projSpeed': 55.0, 'size': 5, 'color': '#ffaa00'},
    'CLOAK100': {'id': 'CLOAK100', 'name': 'Cloak100', 'type': 'UTILITY', 'energyCost': 0.02, 'cooldown': 10000, 'damage': 4500},
    'DAMAGECONTROL': {'id': 'DAMAGECONTROL', 'name': 'Damagecontrol', 'type': 'UTILITY', 'energyCost': 0},
    'DRIVEAFE': {'id': 'DRIVEAFE', 'name': 'Driveafe', 'type': 'UTILITY', 'damage': 60000, 'projSpeed': 1.1},
    'DRIVEAME': {'id': 'DRIVEAME', 'name': 'Driveame', 'type': 'UTILITY', 'damage': 30000, 'projSpeed': 1.2},
    'DRIVEHVAFE': {'id': 'DRIVEHVAFE', 'name': 'Drivehvafe', 'type': 'UTILITY', 'damage': 120000, 'projSpeed': 1.1},
    'DRIVEHVAME': {'id': 'DRIVEHVAME', 'name': 'Drivehvame', 'type': 'UTILITY', 'damage': 60000, 'projSpeed': 1.2},
    'DRIVEHVIE': {'id': 'DRIVEHVIE', 'name': 'Drivehvie', 'type': 'UTILITY', 'damage': 90000, 'projSpeed': 1.0},
    'DRIVEHVPFE': {'id': 'DRIVEHVPFE', 'name': 'Drivehvpfe', 'type': 'UTILITY', 'damage': 60000, 'projSpeed': 0.9},
    'DRIVEHVPIE': {'id': 'DRIVEHVPIE', 'name': 'Drivehvpie', 'type': 'UTILITY', 'damage': 90000, 'projSpeed': 1.0},
    'DRIVEHVSE': {'id': 'DRIVEHVSE', 'name': 'Drivehvse', 'type': 'UTILITY', 'damage': 150000, 'projSpeed': 1.3},
    'DRIVEIE': {'id': 'DRIVEIE', 'name': 'Driveie', 'type': 'UTILITY', 'damage': 45000, 'projSpeed': 1.0},
    'DRIVEPFE': {'id': 'DRIVEPFE', 'name': 'Drivepfe', 'type': 'UTILITY', 'damage': 30000, 'projSpeed': 0.9},
    'DRIVEPIE': {'id': 'DRIVEPIE', 'name': 'Drivepie', 'type': 'UTILITY', 'damage': 45000, 'projSpeed': 1.0},
    'DRIVESE': {'id': 'DRIVESE', 'name': 'Drivese', 'type': 'UTILITY', 'damage': 75000, 'projSpeed': 1.3},
    'DROPPOD': {'id': 'DROPPOD', 'name': 'Droppod', 'type': 'UTILITY', 'damage': 4500, 'range': 300.0},
    'DROPPODMI': {'id': 'DROPPODMI', 'name': 'Droppodmi', 'type': 'UTILITY', 'damage': 4500, 'range': 350.0},
    'ECCM': {'id': 'ECCM', 'name': 'Eccm', 'type': 'UTILITY', 'energyCost': 5, 'damage': 2250, 'range': 1000.0},
    'ECCM1': {'id': 'ECCM1', 'name': 'Eccm1', 'type': 'UTILITY', 'energyCost': 10, 'cooldown': 30000, 'damage': 2500, 'range': 1500.0},
    'ECCM2': {'id': 'ECCM2', 'name': 'Eccm2', 'type': 'UTILITY', 'energyCost': 2, 'cooldown': 2000, 'damage': 2250, 'range': 300.0},
    'ECM': {'id': 'ECM', 'name': 'Ecm', 'type': 'UTILITY', 'energyCost': 5, 'cooldown': 9000, 'damage': 2250, 'range': 500.0},
    'ECM1': {'id': 'ECM1', 'name': 'Ecm1', 'type': 'UTILITY', 'energyCost': 10, 'cooldown': 60000, 'damage': 2500, 'range': 750.0},
    'ECM2': {'id': 'ECM2', 'name': 'Ecm2', 'type': 'UTILITY', 'energyCost': 2, 'cooldown': 2000, 'damage': 2250, 'range': 150.0},
    'ELF750': {'id': 'ELF750', 'name': 'Elf750', 'type': 'UTILITY', 'damage': 3000, 'range': 750.0},
    'EMP500': {'id': 'EMP500', 'name': 'Emp500', 'type': 'UTILITY', 'damage': 1800, 'range': 250.0},
    'FIGHTERBAY': {'id': 'FIGHTERBAY', 'name': 'Fighterbay', 'type': 'WEAPON', 'energyCost': 30, 'cooldown': 1000, 'damage': 1100, 'range': 5, 'projSpeed': 35.0, 'size': 5, 'color': '#ffaa00'},
    'FIGHTERBAYASSAULT': {'id': 'FIGHTERBAYASSAULT', 'name': 'Fighterbayassault', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 1000, 'damage': 1100, 'range': 1, 'projSpeed': 40.0, 'size': 5, 'color': '#ffaa00'},
    'FIGHTERBAYBOMBER': {'id': 'FIGHTERBAYBOMBER', 'name': 'Fighterbaybomber', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 1000, 'damage': 1100, 'range': 1, 'projSpeed': 35.0, 'size': 5, 'color': '#ffaa00'},
    'FIGHTERBAYINTERCEPTOR': {'id': 'FIGHTERBAYINTERCEPTOR', 'name': 'Fighterbayinterceptor', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 1000, 'damage': 1100, 'range': 1, 'projSpeed': 45.0, 'size': 5, 'color': '#ffaa00'},
    'FIGHTERBAYSCOUT': {'id': 'FIGHTERBAYSCOUT', 'name': 'Fighterbayscout', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 1000, 'damage': 0, 'range': 1, 'projSpeed': 35.0, 'size': 5, 'color': '#ffaa00'},
    'FIGHTERBAYTORPEDO': {'id': 'FIGHTERBAYTORPEDO', 'name': 'Fighterbaytorpedo', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 1000, 'damage': 1100, 'range': 1, 'projSpeed': 35.0, 'size': 5, 'color': '#ffaa00'},
    'FOCUSEDTECCM': {'id': 'FOCUSEDTECCM', 'name': 'Focusedteccm', 'type': 'UTILITY', 'energyCost': 2, 'cooldown': 2000, 'damage': 2250, 'range': 450.0},
    'FOCUSEDTECM': {'id': 'FOCUSEDTECM', 'name': 'Focusedtecm', 'type': 'UTILITY', 'energyCost': 2, 'cooldown': 2000, 'damage': 2250, 'range': 225.0},
    'GADGETS': {'id': 'GADGETS', 'name': 'Gadgets', 'type': 'UTILITY'},
    'GADGETSDLL': {'id': 'GADGETSDLL', 'name': 'Gadgetsdll', 'type': 'UTILITY'},
    'INNARDS': {'id': 'INNARDS', 'name': 'Innards', 'type': 'UTILITY', 'damage': 8000},
    'JD1000': {'id': 'JD1000', 'name': 'Jd1000', 'type': 'UTILITY', 'energyCost': 55, 'damage': 4500, 'range': 1000.0},
    'JD2K': {'id': 'JD2K', 'name': 'Jd2K', 'type': 'UTILITY', 'damage': 4500, 'range': 2000.0},
    'JUMPDRIVEANTIMATTER': {'id': 'JUMPDRIVEANTIMATTER', 'name': 'Jumpdriveantimatter', 'type': 'UTILITY', 'energyCost': 3600, 'damage': 28000, 'projSpeed': 3600.0},
    'JUMPDRIVEENERGY': {'id': 'JUMPDRIVEENERGY', 'name': 'Jumpdriveenergy', 'type': 'UTILITY', 'energyCost': 3500, 'damage': 45000, 'projSpeed': 2200.0},
    'JUMPDRIVEHMA': {'id': 'JUMPDRIVEHMA', 'name': 'Jumpdrivehma', 'type': 'UTILITY', 'energyCost': 15000, 'damage': 41500, 'projSpeed': 500.0},
    'JUMPDRIVEOVERDRIVE': {'id': 'JUMPDRIVEOVERDRIVE', 'name': 'Jumpdriveoverdrive', 'type': 'UTILITY', 'energyCost': 1200, 'damage': 37000, 'projSpeed': 90.0},
    'JUMPDRIVESE': {'id': 'JUMPDRIVESE', 'name': 'Jumpdrivese', 'type': 'UTILITY', 'energyCost': 3000, 'damage': 27500},
    'JUMPDRIVETACHYON': {'id': 'JUMPDRIVETACHYON', 'name': 'Jumpdrivetachyon', 'type': 'UTILITY', 'energyCost': 2400, 'damage': 37000, 'projSpeed': 2400.0},
    'JUMPGATE1': {'id': 'JUMPGATE1', 'name': 'Jumpgate1', 'type': 'UTILITY', 'damage': 8750, 'range': 5000.0},
    'JUMPGATE2': {'id': 'JUMPGATE2', 'name': 'Jumpgate2', 'type': 'UTILITY', 'damage': 12250, 'range': 5000.0},
    'LOCALECM': {'id': 'LOCALECM', 'name': 'Localecm', 'type': 'UTILITY', 'energyCost': 2, 'damage': 2500, 'range': 5.0},
    'LONGWAVEECCM': {'id': 'LONGWAVEECCM', 'name': 'Longwaveeccm', 'type': 'UTILITY', 'energyCost': 2, 'cooldown': 3000, 'damage': 2250, 'range': 450.0},
    'LONGWAVEECM': {'id': 'LONGWAVEECM', 'name': 'Longwaveecm', 'type': 'UTILITY', 'energyCost': 2, 'cooldown': 3000, 'damage': 2250, 'range': 225.0},
    'MININGBEAM': {'id': 'MININGBEAM', 'name': 'Miningbeam', 'type': 'UTILITY', 'energyCost': 4, 'damage': 4200, 'range': 300.0},
    'MOUTHBEAM': {'id': 'MOUTHBEAM', 'name': 'Mouthbeam', 'type': 'WEAPON', 'energyCost': 5400, 'damage': 200, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'NANITEINJECTOR': {'id': 'NANITEINJECTOR', 'name': 'Naniteinjector', 'type': 'UTILITY', 'energyCost': 0},
    'NARROWBANDTECCM': {'id': 'NARROWBANDTECCM', 'name': 'Narrowbandteccm', 'type': 'UTILITY', 'energyCost': 2, 'damage': 2250, 'range': 300.0},
    'NARROWBANDTECM': {'id': 'NARROWBANDTECM', 'name': 'Narrowbandtecm', 'type': 'UTILITY', 'energyCost': 2, 'damage': 2250, 'range': 150.0},
    'PLANETARENA': {'id': 'PLANETARENA', 'name': 'Planetarena', 'type': 'UTILITY'},
    'PLANETARID': {'id': 'PLANETARID', 'name': 'Planetarid', 'type': 'UTILITY'},
    'PLANETBARREN': {'id': 'PLANETBARREN', 'name': 'Planetbarren', 'type': 'UTILITY'},
    'PLANETGAS': {'id': 'PLANETGAS', 'name': 'Planetgas', 'type': 'UTILITY'},
    'PLANETHOME': {'id': 'PLANETHOME', 'name': 'Planethome', 'type': 'UTILITY'},
    'PLANETICE': {'id': 'PLANETICE', 'name': 'Planetice', 'type': 'UTILITY'},
    'PLANETINFERNO': {'id': 'PLANETINFERNO', 'name': 'Planetinferno', 'type': 'UTILITY'},
    'PLANETMOON': {'id': 'PLANETMOON', 'name': 'Planetmoon', 'type': 'UTILITY'},
    'PLANETOCEAN': {'id': 'PLANETOCEAN', 'name': 'Planetocean', 'type': 'UTILITY'},
    'PLANETTERRAN': {'id': 'PLANETTERRAN', 'name': 'Planetterran', 'type': 'UTILITY'},
    'PLATFORMDEFENSE': {'id': 'PLATFORMDEFENSE', 'name': 'Platformdefense', 'type': 'DEFENSE', 'damage': 95000, 'projSpeed': 0.0},
    'PLATFORMSENSOR': {'id': 'PLATFORMSENSOR', 'name': 'Platformsensor', 'type': 'UTILITY', 'damage': 80000, 'projSpeed': 0.0},
    'PLATFORMSUPPLY': {'id': 'PLATFORMSUPPLY', 'name': 'Platformsupply', 'type': 'UTILITY', 'damage': 125000, 'projSpeed': 0.0},
    'PULSESHIELD': {'id': 'PULSESHIELD', 'name': 'Pulseshield', 'type': 'DEFENSE', 'damage': 600, 'range': 300.0},
    'QUANTUMHIGGSNET': {'id': 'QUANTUMHIGGSNET', 'name': 'Quantumhiggsnet', 'type': 'UTILITY', 'energyCost': 10, 'cooldown': 30000, 'range': 300.0},
    'REACTOR1000': {'id': 'REACTOR1000', 'name': 'Reactor1000', 'type': 'UTILITY', 'damage': 4500},
    'REACTOR1500': {'id': 'REACTOR1500', 'name': 'Reactor1500', 'type': 'UTILITY', 'damage': 4500},
    'REACTOR500': {'id': 'REACTOR500', 'name': 'Reactor500', 'type': 'UTILITY', 'damage': 1975},
    'REACTORAUX': {'id': 'REACTORAUX', 'name': 'Reactoraux', 'type': 'UTILITY', 'damage': 4500},
    'REDUCEWEAPONRANGE': {'id': 'REDUCEWEAPONRANGE', 'name': 'Reduceweaponrange', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 30000, 'range': 300.0, 'damage': 25, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'RF250': {'id': 'RF250', 'name': 'Rf250', 'type': 'UTILITY', 'energyCost': 30, 'damage': 4500, 'range': 250.0},
    'SCANNER': {'id': 'SCANNER', 'name': 'Scanner', 'type': 'UTILITY', 'energyCost': 5, 'damage': 2250},
    'SCANNER1': {'id': 'SCANNER1', 'name': 'Scanner1', 'type': 'UTILITY', 'energyCost': 1, 'damage': 1200},
    'SCANNER2': {'id': 'SCANNER2', 'name': 'Scanner2', 'type': 'UTILITY', 'energyCost': 5, 'damage': 2250},
    'SCANNERDETECTCLOAK': {'id': 'SCANNERDETECTCLOAK', 'name': 'Scannerdetectcloak', 'type': 'UTILITY', 'energyCost': 10, 'damage': 2700},
    'SHIELDACTIVE': {'id': 'SHIELDACTIVE', 'name': 'Shieldactive', 'type': 'DEFENSE', 'energyCost': 2, 'damage': 5700},
    'SHIELDAUXILLARY': {'id': 'SHIELDAUXILLARY', 'name': 'Shieldauxillary', 'type': 'DEFENSE', 'energyCost': 0, 'damage': 3000},
    'SHIELDGHOST': {'id': 'SHIELDGHOST', 'name': 'Shieldghost', 'type': 'DEFENSE', 'energyCost': 4, 'damage': 4000},
    'SHIELDKLUTHPT': {'id': 'SHIELDKLUTHPT', 'name': 'Shieldkluthpt', 'type': 'DEFENSE', 'damage': 5700},
    'SHIELDPLANETARY': {'id': 'SHIELDPLANETARY', 'name': 'Shieldplanetary', 'type': 'DEFENSE', 'energyCost': 0, 'damage': 12000},
    'SHIELDREACTIVE': {'id': 'SHIELDREACTIVE', 'name': 'Shieldreactive', 'type': 'DEFENSE', 'energyCost': 2, 'damage': 6000},
    'SHIELDSKIRMISH': {'id': 'SHIELDSKIRMISH', 'name': 'Shieldskirmish', 'type': 'DEFENSE', 'energyCost': 4, 'damage': 4000},
    'SHIPCRUISER': {'id': 'SHIPCRUISER', 'name': 'Shipcruiser', 'type': 'UTILITY', 'damage': 95000, 'projSpeed': 5.0},
    'SHIPDESTROYER': {'id': 'SHIPDESTROYER', 'name': 'Shipdestroyer', 'type': 'UTILITY', 'damage': 40000, 'projSpeed': 7.0},
    'SHIPDREAD': {'id': 'SHIPDREAD', 'name': 'Shipdread', 'type': 'UTILITY', 'damage': 208000, 'projSpeed': 3.0},
    'SHIPDREAD2': {'id': 'SHIPDREAD2', 'name': 'Shipdread2', 'type': 'UTILITY', 'damage': 208000, 'projSpeed': 3.0},
    'SHIPENGINEER': {'id': 'SHIPENGINEER', 'name': 'Shipengineer', 'type': 'UTILITY', 'damage': 32000, 'projSpeed': 10.0},
    'SHIPFRIGATE': {'id': 'SHIPFRIGATE', 'name': 'Shipfrigate', 'type': 'UTILITY', 'damage': 20000, 'projSpeed': 10.0},
    'SHIPNODE': {'id': 'SHIPNODE', 'name': 'Shipnode', 'type': 'UTILITY', 'damage': 750000, 'projSpeed': 5.0},
    'SHIPORB': {'id': 'SHIPORB', 'name': 'Shiporb', 'type': 'UTILITY', 'damage': 2500000, 'projSpeed': 10.0},
    'SHIPSCOUT': {'id': 'SHIPSCOUT', 'name': 'Shipscout', 'type': 'UTILITY', 'damage': 10000, 'projSpeed': 14.0},
    'SHIPSTATION': {'id': 'SHIPSTATION', 'name': 'Shipstation', 'type': 'UTILITY', 'damage': 500000, 'projSpeed': 1.0},
    'SHIPSUPPLY': {'id': 'SHIPSUPPLY', 'name': 'Shipsupply', 'type': 'UTILITY', 'damage': 48000, 'projSpeed': 10.0},
    'SHIPTRANSPORT': {'id': 'SHIPTRANSPORT', 'name': 'Shiptransport', 'type': 'UTILITY', 'damage': 28000, 'projSpeed': 10.0},
    'SUPPLYDRONES': {'id': 'SUPPLYDRONES', 'name': 'Supplydrones', 'type': 'UTILITY', 'range': 250.0},
    'SUPPLYDRONESLIGHT': {'id': 'SUPPLYDRONESLIGHT', 'name': 'Supplydroneslight', 'type': 'UTILITY', 'range': 250.0},
    'SUPPLYDRONESPLANETARY': {'id': 'SUPPLYDRONESPLANETARY', 'name': 'Supplydronesplanetary', 'type': 'UTILITY', 'range': 500.0},
    'SUPPLYDRONESSTATION': {'id': 'SUPPLYDRONESSTATION', 'name': 'Supplydronesstation', 'type': 'UTILITY', 'range': 500.0},
    'TACTICALECCM': {'id': 'TACTICALECCM', 'name': 'Tacticaleccm', 'type': 'UTILITY', 'energyCost': 1, 'cooldown': 6000, 'damage': 2250, 'range': 900.0},
    'TACTICALECM': {'id': 'TACTICALECM', 'name': 'Tacticalecm', 'type': 'UTILITY', 'energyCost': 1, 'cooldown': 6000, 'damage': 2250, 'range': 450.0},
    'TRACTORBEAM300': {'id': 'TRACTORBEAM300', 'name': 'Tractorbeam300', 'type': 'WEAPON', 'energyCost': 1, 'cooldown': 2000, 'damage': 6000, 'range': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'UNITARMOR': {'id': 'UNITARMOR', 'name': 'Unitarmor', 'type': 'DEFENSE', 'damage': 200, 'range': 1},
    'UNITAUTOMATON': {'id': 'UNITAUTOMATON', 'name': 'Unitautomaton', 'type': 'UTILITY', 'damage': 200, 'range': 1},
    'UNITHEAVYINFANTRY': {'id': 'UNITHEAVYINFANTRY', 'name': 'Unitheavyinfantry', 'type': 'UTILITY', 'damage': 150, 'range': 0},
    'UNITINFANTRY': {'id': 'UNITINFANTRY', 'name': 'Unitinfantry', 'type': 'UTILITY', 'damage': 100, 'range': 0},
    'UNITRAIDINGPARTY': {'id': 'UNITRAIDINGPARTY', 'name': 'Unitraidingparty', 'type': 'UTILITY', 'damage': 125, 'range': 1},
    'UNITSPY': {'id': 'UNITSPY', 'name': 'Unitspy', 'type': 'UTILITY', 'damage': 100, 'range': 0},
    'WEAPONAMMINE': {'id': 'WEAPONAMMINE', 'name': 'Weaponammine', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 900, 'range': 10, 'projSpeed': 10, 'size': 5, 'color': '#ffaa00'},
    'WEAPONAMPLIFIEDCOILBEAM': {'id': 'WEAPONAMPLIFIEDCOILBEAM', 'name': 'Weaponamplifiedcoilbeam', 'type': 'WEAPON', 'energyCost': 300, 'damage': 90, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONAMPLIFIEDPULSEBEAM': {'id': 'WEAPONAMPLIFIEDPULSEBEAM', 'name': 'Weaponamplifiedpulsebeam', 'type': 'WEAPON', 'energyCost': 700, 'damage': 10, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONAMTORPEDO': {'id': 'WEAPONAMTORPEDO', 'name': 'Weaponamtorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1050, 'range': 4, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONAMTORPEDOFIGHTER': {'id': 'WEAPONAMTORPEDOFIGHTER', 'name': 'Weaponamtorpedofighter', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 0, 'damage': 1500, 'range': 6, 'projSpeed': 80.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONANTIRADARMISSILE': {'id': 'WEAPONANTIRADARMISSILE', 'name': 'Weaponantiradarmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 3, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONANTISHIPMISSILE': {'id': 'WEAPONANTISHIPMISSILE', 'name': 'Weaponantishipmissile', 'type': 'WEAPON', 'energyCost': 20, 'cooldown': 1000, 'damage': 480, 'range': 6, 'projSpeed': 90.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONARESCANNON': {'id': 'WEAPONARESCANNON', 'name': 'Weaponarescannon', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 1000, 'damage': 0, 'range': 40, 'projSpeed': 200.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONARMISSILE': {'id': 'WEAPONARMISSILE', 'name': 'Weaponarmissile', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 1000, 'damage': 1000, 'range': 20, 'projSpeed': 85.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONARMISSILE2': {'id': 'WEAPONARMISSILE2', 'name': 'Weaponarmissile2', 'type': 'WEAPON', 'energyCost': 600, 'cooldown': 1000, 'damage': 1000, 'range': 20, 'projSpeed': 85.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONASMISSILE': {'id': 'WEAPONASMISSILE', 'name': 'Weaponasmissile', 'type': 'WEAPON', 'energyCost': 20, 'cooldown': 3000, 'damage': 480, 'range': 6, 'projSpeed': 90.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONBBBOMB': {'id': 'WEAPONBBBOMB', 'name': 'Weaponbbbomb', 'type': 'WEAPON', 'energyCost': 600, 'cooldown': 0, 'damage': 387, 'range': 1, 'projSpeed': 35.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONBPCBOMB': {'id': 'WEAPONBPCBOMB', 'name': 'Weaponbpcbomb', 'type': 'WEAPON', 'energyCost': 1, 'cooldown': 1000, 'damage': 1100, 'range': 12, 'projSpeed': 1.5, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCL': {'id': 'WEAPONCL', 'name': 'Weaponcl', 'type': 'WEAPON', 'energyCost': 720, 'damage': 30, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCL1000': {'id': 'WEAPONCL1000', 'name': 'Weaponcl1000', 'type': 'WEAPON', 'energyCost': 3600, 'damage': 132, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCL2000': {'id': 'WEAPONCL2000', 'name': 'Weaponcl2000', 'type': 'WEAPON', 'energyCost': 7500, 'damage': 198, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCL300': {'id': 'WEAPONCL300', 'name': 'Weaponcl300', 'type': 'WEAPON', 'energyCost': 600, 'damage': 33, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCL500': {'id': 'WEAPONCL500', 'name': 'Weaponcl500', 'type': 'WEAPON', 'energyCost': 1400, 'damage': 66, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCLER': {'id': 'WEAPONCLER', 'name': 'Weaponcler', 'type': 'WEAPON', 'energyCost': 600, 'damage': 10, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCLH': {'id': 'WEAPONCLH', 'name': 'Weaponclh', 'type': 'WEAPON', 'energyCost': 2880, 'damage': 120, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCLHICC': {'id': 'WEAPONCLHICC', 'name': 'Weaponclhicc', 'type': 'WEAPON', 'energyCost': 1920, 'damage': 120, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCLICC': {'id': 'WEAPONCLICC', 'name': 'Weaponclicc', 'type': 'WEAPON', 'energyCost': 480, 'damage': 30, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONCLPLANET': {'id': 'WEAPONCLPLANET', 'name': 'Weaponclplanet', 'type': 'WEAPON', 'energyCost': 1100, 'damage': 56, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONDEATHBEAM': {'id': 'WEAPONDEATHBEAM', 'name': 'Weapondeathbeam', 'type': 'WEAPON', 'energyCost': 6000, 'damage': 5000, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONDISRUPTOR': {'id': 'WEAPONDISRUPTOR', 'name': 'Weapondisruptor', 'type': 'WEAPON', 'energyCost': 1000, 'damage': 25, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONDISRUPTORA': {'id': 'WEAPONDISRUPTORA', 'name': 'Weapondisruptora', 'type': 'WEAPON', 'energyCost': 4000, 'damage': 100, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONDMC': {'id': 'WEAPONDMC', 'name': 'Weapondmc', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 13125, 'range': 4, 'projSpeed': 10.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONDSBEAM': {'id': 'WEAPONDSBEAM', 'name': 'Weapondsbeam', 'type': 'WEAPON', 'energyCost': 5400, 'damage': 60, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONELF': {'id': 'WEAPONELF', 'name': 'Weaponelf', 'type': 'WEAPON', 'energyCost': 1000, 'damage': 50, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONELFTORPEDO': {'id': 'WEAPONELFTORPEDO', 'name': 'Weaponelftorpedo', 'type': 'WEAPON', 'energyCost': 210, 'cooldown': 0, 'damage': 175, 'range': 9, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONEMPCANNON': {'id': 'WEAPONEMPCANNON', 'name': 'Weaponempcannon', 'type': 'WEAPON', 'energyCost': 280, 'cooldown': 0, 'damage': 0, 'range': 12, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONEMPCANNONHV': {'id': 'WEAPONEMPCANNONHV', 'name': 'Weaponempcannonhv', 'type': 'WEAPON', 'energyCost': 560, 'cooldown': 0, 'damage': 0, 'range': 12, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONEMPMINE': {'id': 'WEAPONEMPMINE', 'name': 'Weaponempmine', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1500, 'range': 10, 'projSpeed': 10, 'size': 5, 'color': '#ffaa00'},
    'WEAPONEMPMISSILE': {'id': 'WEAPONEMPMISSILE', 'name': 'Weaponempmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1500, 'range': 10, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONEMPMISSILEHV': {'id': 'WEAPONEMPMISSILEHV', 'name': 'Weaponempmissilehv', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1500, 'range': 10, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONEMPTORPEDO': {'id': 'WEAPONEMPTORPEDO', 'name': 'Weaponemptorpedo', 'type': 'WEAPON', 'energyCost': 360, 'cooldown': 1000, 'damage': 1400, 'range': 5, 'projSpeed': 55.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONETORPEDO': {'id': 'WEAPONETORPEDO', 'name': 'Weaponetorpedo', 'type': 'WEAPON', 'energyCost': 750, 'cooldown': 0, 'damage': 0, 'range': 4, 'projSpeed': 8.5, 'size': 5, 'color': '#ffaa00'},
    'WEAPONFEP': {'id': 'WEAPONFEP', 'name': 'Weaponfep', 'type': 'WEAPON', 'energyCost': 1320, 'damage': 45, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONFEPO': {'id': 'WEAPONFEPO', 'name': 'Weaponfepo', 'type': 'WEAPON', 'energyCost': 5280, 'damage': 180, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONFIGHTERBEAM': {'id': 'WEAPONFIGHTERBEAM', 'name': 'Weaponfighterbeam', 'type': 'WEAPON', 'energyCost': 400, 'damage': 2, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONFLUXBEAM': {'id': 'WEAPONFLUXBEAM', 'name': 'Weaponfluxbeam', 'type': 'WEAPON', 'energyCost': 1440, 'damage': 60, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONFLUXWAVE': {'id': 'WEAPONFLUXWAVE', 'name': 'Weaponfluxwave', 'type': 'WEAPON', 'damage': 5100, 'range': 300.0, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONFURYBOMB': {'id': 'WEAPONFURYBOMB', 'name': 'Weaponfurybomb', 'type': 'WEAPON', 'energyCost': 600, 'cooldown': 0, 'damage': 387, 'range': 1, 'projSpeed': 35.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONFUSIONTORPEDO': {'id': 'WEAPONFUSIONTORPEDO', 'name': 'Weaponfusiontorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1575, 'range': 6, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONGAUSS': {'id': 'WEAPONGAUSS', 'name': 'Weapongauss', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 15, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONGAUSSHV': {'id': 'WEAPONGAUSSHV', 'name': 'Weapongausshv', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 6, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONGUARDIANMISSILE': {'id': 'WEAPONGUARDIANMISSILE', 'name': 'Weaponguardianmissile', 'type': 'WEAPON', 'energyCost': 1400, 'cooldown': 1000, 'damage': 6750, 'range': 20, 'projSpeed': 65.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONHAMMINE': {'id': 'WEAPONHAMMINE', 'name': 'Weaponhammine', 'type': 'WEAPON', 'energyCost': 270, 'cooldown': 2000, 'damage': 2079, 'range': 20, 'projSpeed': 6.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONHARPEXMISSILE': {'id': 'WEAPONHARPEXMISSILE', 'name': 'Weaponharpexmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 3600, 'range': 8, 'projSpeed': 2.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONHEAVYMASSDRIVER': {'id': 'WEAPONHEAVYMASSDRIVER', 'name': 'Weaponheavymassdriver', 'type': 'WEAPON', 'energyCost': 2, 'cooldown': 2000, 'damage': 0, 'range': 8, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONHEMPMINE': {'id': 'WEAPONHEMPMINE', 'name': 'Weaponhempmine', 'type': 'WEAPON', 'energyCost': 320, 'cooldown': 2000, 'damage': 1962, 'range': 20, 'projSpeed': 6.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONHTNMINE': {'id': 'WEAPONHTNMINE', 'name': 'Weaponhtnmine', 'type': 'WEAPON', 'energyCost': 320, 'cooldown': 2000, 'damage': 1062, 'range': 20, 'projSpeed': 6.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIEMISSILE': {'id': 'WEAPONIEMISSILE', 'name': 'Weaponiemissile', 'type': 'WEAPON', 'energyCost': 800, 'cooldown': 1000, 'damage': 2700, 'range': 5, 'projSpeed': 70.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIEMISSILE2': {'id': 'WEAPONIEMISSILE2', 'name': 'Weaponiemissile2', 'type': 'WEAPON', 'energyCost': 1600, 'cooldown': 1000, 'damage': 2700, 'range': 10, 'projSpeed': 70.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIONCANNON': {'id': 'WEAPONIONCANNON', 'name': 'Weaponioncannon', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 8, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIONIZEDBEAMCANNON': {'id': 'WEAPONIONIZEDBEAMCANNON', 'name': 'Weaponionizedbeamcannon', 'type': 'WEAPON', 'energyCost': 100, 'damage': 60, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIONTORPEDO': {'id': 'WEAPONIONTORPEDO', 'name': 'Weaponiontorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1080, 'range': 5, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIONTRACKERMISSILE': {'id': 'WEAPONIONTRACKERMISSILE', 'name': 'Weaponiontrackermissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1800, 'range': 10, 'projSpeed': 2.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIPBEAM': {'id': 'WEAPONIPBEAM', 'name': 'Weaponipbeam', 'type': 'WEAPON', 'energyCost': 300, 'damage': 150, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONIPSBEAM': {'id': 'WEAPONIPSBEAM', 'name': 'Weaponipsbeam', 'type': 'WEAPON', 'energyCost': 300, 'damage': 180, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONLINEARDRIVEMISSILE': {'id': 'WEAPONLINEARDRIVEMISSILE', 'name': 'Weaponlineardrivemissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 3, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONLONGINUSDEFENSEBEAM': {'id': 'WEAPONLONGINUSDEFENSEBEAM', 'name': 'Weaponlonginusdefensebeam', 'type': 'WEAPON', 'energyCost': 360, 'damage': 10, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONMASSPULSECANNON': {'id': 'WEAPONMASSPULSECANNON', 'name': 'Weaponmasspulsecannon', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 1000, 'damage': 0, 'range': 24, 'projSpeed': 200.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONMIRVBOMB': {'id': 'WEAPONMIRVBOMB', 'name': 'Weaponmirvbomb', 'type': 'WEAPON', 'energyCost': 1, 'cooldown': 1000, 'damage': 620, 'range': 12, 'projSpeed': 20.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONMPA': {'id': 'WEAPONMPA', 'name': 'Weaponmpa', 'type': 'WEAPON', 'energyCost': 800, 'cooldown': 0, 'damage': 0, 'range': 15, 'projSpeed': 40.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONNEUTRONBOMB': {'id': 'WEAPONNEUTRONBOMB', 'name': 'Weaponneutronbomb', 'type': 'WEAPON', 'energyCost': 3, 'cooldown': 3000, 'damage': 900, 'range': 12, 'projSpeed': 1.5, 'size': 5, 'color': '#ffaa00'},
    'WEAPONNEUTRONIUMSIEGETORPEDO': {'id': 'WEAPONNEUTRONIUMSIEGETORPEDO', 'name': 'Weaponneutroniumsiegetorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 5250, 'range': 12, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONNEUTRONIUMTORPEDO': {'id': 'WEAPONNEUTRONIUMTORPEDO', 'name': 'Weaponneutroniumtorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 5250, 'range': 4, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPARTICLECANNON': {'id': 'WEAPONPARTICLECANNON', 'name': 'Weaponparticlecannon', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 0, 'damage': 0, 'range': 24, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPARTICLECANNONFIGHTER': {'id': 'WEAPONPARTICLECANNONFIGHTER', 'name': 'Weaponparticlecannonfighter', 'type': 'WEAPON', 'energyCost': 70, 'cooldown': 0, 'damage': 0, 'range': 20, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPARTICLECANNONHV': {'id': 'WEAPONPARTICLECANNONHV', 'name': 'Weaponparticlecannonhv', 'type': 'WEAPON', 'energyCost': 600, 'cooldown': 0, 'damage': 0, 'range': 24, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPASSERIDAEMISSILELAUNCHER': {'id': 'WEAPONPASSERIDAEMISSILELAUNCHER', 'name': 'Weaponpasseridaemissilelauncher', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1500, 'range': 20, 'projSpeed': 15.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPCMISSILE': {'id': 'WEAPONPCMISSILE', 'name': 'Weaponpcmissile', 'type': 'WEAPON', 'energyCost': 1500, 'cooldown': 1000, 'damage': 6500, 'range': 12, 'projSpeed': 50.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPEREGRINEMISSILE': {'id': 'WEAPONPEREGRINEMISSILE', 'name': 'Weaponperegrinemissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 3, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPHOENIXMISSILE': {'id': 'WEAPONPHOENIXMISSILE', 'name': 'Weaponphoenixmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 3000, 'range': 8, 'projSpeed': 2.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPLASMACANNON': {'id': 'WEAPONPLASMACANNON', 'name': 'Weaponplasmacannon', 'type': 'WEAPON', 'energyCost': 720, 'cooldown': 0, 'damage': 225, 'range': 9, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPLASMACANNONHV': {'id': 'WEAPONPLASMACANNONHV', 'name': 'Weaponplasmacannonhv', 'type': 'WEAPON', 'energyCost': 1440, 'cooldown': 0, 'damage': 450, 'range': 9, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPROTONCRUISEMISSILE': {'id': 'WEAPONPROTONCRUISEMISSILE', 'name': 'Weaponprotoncruisemissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 2025, 'range': 8, 'projSpeed': 8.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPROTONTORPEDO': {'id': 'WEAPONPROTONTORPEDO', 'name': 'Weaponprotontorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1575, 'range': 5, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPROTONTORPEDOFIGHTER': {'id': 'WEAPONPROTONTORPEDOFIGHTER', 'name': 'Weaponprotontorpedofighter', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 0, 'damage': 2700, 'range': 6, 'projSpeed': 100.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSGMISSILE': {'id': 'WEAPONPSGMISSILE', 'name': 'Weaponpsgmissile', 'type': 'WEAPON', 'energyCost': 600, 'cooldown': 2000, 'damage': 2135, 'range': 20, 'projSpeed': 80.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSGMISSILE2': {'id': 'WEAPONPSGMISSILE2', 'name': 'Weaponpsgmissile2', 'type': 'WEAPON', 'energyCost': 1200, 'cooldown': 2000, 'damage': 2550, 'range': 6, 'projSpeed': 80.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSIBEAM': {'id': 'WEAPONPSIBEAM', 'name': 'Weaponpsibeam', 'type': 'WEAPON', 'energyCost': 50, 'damage': 90, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSICANNON': {'id': 'WEAPONPSICANNON', 'name': 'Weaponpsicannon', 'type': 'WEAPON', 'energyCost': 400, 'cooldown': 0, 'damage': 0, 'range': 15, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSICANNONFIGHTER': {'id': 'WEAPONPSICANNONFIGHTER', 'name': 'Weaponpsicannonfighter', 'type': 'WEAPON', 'energyCost': 70, 'cooldown': 0, 'damage': 0, 'range': 20, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSICANNONHV': {'id': 'WEAPONPSICANNONHV', 'name': 'Weaponpsicannonhv', 'type': 'WEAPON', 'energyCost': 800, 'cooldown': 0, 'damage': 0, 'range': 15, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSIFOCUSEDDISRUPTOR': {'id': 'WEAPONPSIFOCUSEDDISRUPTOR', 'name': 'Weaponpsifocuseddisruptor', 'type': 'WEAPON', 'energyCost': 800, 'damage': 20, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSIONICMISSILE': {'id': 'WEAPONPSIONICMISSILE', 'name': 'Weaponpsionicmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 3, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSIWAVESEEKERMISSILE': {'id': 'WEAPONPSIWAVESEEKERMISSILE', 'name': 'Weaponpsiwaveseekermissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1013, 'range': 8, 'projSpeed': 8.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPSMISSILE': {'id': 'WEAPONPSMISSILE', 'name': 'Weaponpsmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1500, 'range': 8, 'projSpeed': 12.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPULSEBEAM': {'id': 'WEAPONPULSEBEAM', 'name': 'Weaponpulsebeam', 'type': 'WEAPON', 'energyCost': 240, 'damage': 10, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONPURIFIERBOMB': {'id': 'WEAPONPURIFIERBOMB', 'name': 'Weaponpurifierbomb', 'type': 'WEAPON', 'energyCost': 600, 'cooldown': 0, 'damage': 262, 'range': 1, 'projSpeed': 35.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONQSBOMB': {'id': 'WEAPONQSBOMB', 'name': 'Weaponqsbomb', 'type': 'WEAPON', 'energyCost': 200000, 'cooldown': 1000, 'damage': 800000, 'range': 1, 'projSpeed': 10.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONQSST': {'id': 'WEAPONQSST', 'name': 'Weaponqsst', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 7875, 'range': 12, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONQST': {'id': 'WEAPONQST', 'name': 'Weaponqst', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 7875, 'range': 4, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONRAILGUN': {'id': 'WEAPONRAILGUN', 'name': 'Weaponrailgun', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 18, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONRAILGUNFIGHTER': {'id': 'WEAPONRAILGUNFIGHTER', 'name': 'Weaponrailgunfighter', 'type': 'WEAPON', 'energyCost': 70, 'cooldown': 0, 'damage': 0, 'range': 20, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONRAILGUNHV': {'id': 'WEAPONRAILGUNHV', 'name': 'Weaponrailgunhv', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 15, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONRAPIDCYCLEDISRUPTOR': {'id': 'WEAPONRAPIDCYCLEDISRUPTOR', 'name': 'Weaponrapidcycledisruptor', 'type': 'WEAPON', 'energyCost': 480, 'damage': 20, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONRAPTORMISSILE': {'id': 'WEAPONRAPTORMISSILE', 'name': 'Weaponraptormissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 3, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONS': {'id': 'WEAPONS', 'name': 'Weapons', 'type': 'WEAPON', 'damage': 25, 'range': 1000, 'cooldown': 1000, 'projSpeed': 30, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSABOT': {'id': 'WEAPONSABOT', 'name': 'Weaponsabot', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 12, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSABOT2': {'id': 'WEAPONSABOT2', 'name': 'Weaponsabot2', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 0, 'damage': 1800, 'range': 12, 'projSpeed': 120.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSHOCKMISSILE': {'id': 'WEAPONSHOCKMISSILE', 'name': 'Weaponshockmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 0, 'range': 3, 'projSpeed': 5.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSHREDDERMISSILE': {'id': 'WEAPONSHREDDERMISSILE', 'name': 'Weaponshreddermissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 900, 'range': 20, 'projSpeed': 2.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSHREDDERMISSILE2': {'id': 'WEAPONSHREDDERMISSILE2', 'name': 'Weaponshreddermissile2', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 1000, 'damage': 504, 'range': 30, 'projSpeed': 95.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSHROUDMISSILE': {'id': 'WEAPONSHROUDMISSILE', 'name': 'Weaponshroudmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1800, 'range': 5, 'projSpeed': 2.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSPARROWMISSILE': {'id': 'WEAPONSPARROWMISSILE', 'name': 'Weaponsparrowmissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1500, 'range': 10, 'projSpeed': 2.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSPREADSHOT': {'id': 'WEAPONSPREADSHOT', 'name': 'Weaponspreadshot', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 0, 'damage': 0, 'range': 18, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONSTELLARINCINERATOR': {'id': 'WEAPONSTELLARINCINERATOR', 'name': 'Weaponstellarincinerator', 'type': 'WEAPON', 'energyCost': 2400, 'cooldown': 0, 'damage': 0, 'range': 4, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONTKBOMB': {'id': 'WEAPONTKBOMB', 'name': 'Weapontkbomb', 'type': 'WEAPON', 'energyCost': 1, 'cooldown': 1000, 'damage': 420, 'range': 12, 'projSpeed': 12, 'size': 5, 'color': '#ffaa00'},
    'WEAPONTKCANNON': {'id': 'WEAPONTKCANNON', 'name': 'Weapontkcannon', 'type': 'WEAPON', 'energyCost': 15, 'cooldown': 0, 'damage': 60, 'range': 1, 'projSpeed': 200.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONTKTORPEDO': {'id': 'WEAPONTKTORPEDO', 'name': 'Weapontktorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 735, 'range': 4, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONTNMINE': {'id': 'WEAPONTNMINE', 'name': 'Weapontnmine', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1800, 'range': 10, 'projSpeed': 10, 'size': 5, 'color': '#ffaa00'},
    'WEAPONTREBUCHETSIEGEMISSILE': {'id': 'WEAPONTREBUCHETSIEGEMISSILE', 'name': 'Weapontrebuchetsiegemissile', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 1688, 'range': 8, 'projSpeed': 8.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONVALENCEAUTOCANNON': {'id': 'WEAPONVALENCEAUTOCANNON', 'name': 'Weaponvalenceautocannon', 'type': 'WEAPON', 'energyCost': 160, 'cooldown': 0, 'damage': 0, 'range': 24, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONVALENCEAUTOCANNONHV': {'id': 'WEAPONVALENCEAUTOCANNONHV', 'name': 'Weaponvalenceautocannonhv', 'type': 'WEAPON', 'energyCost': 320, 'cooldown': 0, 'damage': 0, 'range': 24, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONVARIANCESIEGETORPEDO': {'id': 'WEAPONVARIANCESIEGETORPEDO', 'name': 'Weaponvariancesiegetorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 7875, 'range': 12, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONVARIANCETORPEDO': {'id': 'WEAPONVARIANCETORPEDO', 'name': 'Weaponvariancetorpedo', 'type': 'WEAPON', 'energyCost': 10, 'cooldown': 10000, 'damage': 7875, 'range': 2, 'projSpeed': 4.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONWIBBLECANNON': {'id': 'WEAPONWIBBLECANNON', 'name': 'Weaponwibblecannon', 'type': 'WEAPON', 'energyCost': 300, 'cooldown': 0, 'damage': 0, 'range': 18, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
    'WEAPONWIBBLECANNONHV': {'id': 'WEAPONWIBBLECANNONHV', 'name': 'Weaponwibblecannonhv', 'type': 'WEAPON', 'energyCost': 600, 'cooldown': 0, 'damage': 0, 'range': 18, 'projSpeed': 0.0, 'size': 5, 'color': '#ffaa00'},
};
